# Generated by Django 5.1.6 on 2025-02-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoveRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('non_binary', 'Non-Binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=50)),
                ('looking_for', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('non_binary', 'Non-Binary'), ('any', 'Any')], max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
